### ISSUE TITLE
In face_mask_adding, it made some noise on the image  ,when using 'Speed Up'  method.

### ISSUE THREAD

**Issue by luckycaicai** [JDAI-CV/FaceX-Zoo#78]
original image:
![image](https://user-images.githubusercontent.com/41863500/119775840-bef6a700-bef6-11eb-9a29-535090a3a673.png)

1. add mask with "no speed up":
![image](https://user-images.githubusercontent.com/41863500/119775957-e51c4700-bef6-11eb-968a-9c5709872f5a.png)

2. add mask with "speed up":
![image](https://user-images.githubusercontent.com/41863500/119775813-b30ae500-bef6-11eb-884b-e9b618d29e55.png)

**Comment by luckycaicai** [comment]
And the noise randomly occurred each time I ran, the follows the results of 4 experiments :
![image](https://user-images.githubusercontent.com/41863500/119778944-b011f380-befa-11eb-995f-30878a7b1fdf.png)

**Comment by cbwces** [comment]
try  using `    cdef numpy.ndarray[double, ndim=3, mode='c'] image = numpy.zeros((h, w, c), dtype=numpy.double)`instead of`cdef numpy.ndarray[double, ndim=3, mode='c'] image = numpy.empty((h, w, c), dtype=numpy.double)` at 57th line in **FaceX-Zoo/addition_module/face_mask_adding/FMA-3D/utils/cython/render.pyx**, then re-compile file

**Comment by luckycaicai** [comment]
> try using ` cdef numpy.ndarray[double, ndim=3, mode='c'] image = numpy.zeros((h, w, c), dtype=numpy.double)`instead of`cdef numpy.ndarray[double, ndim=3, mode='c'] image = numpy.empty((h, w, c), dtype=numpy.double)` at 57th line in **FaceX-Zoo/addition_module/face_mask_adding/FMA-3D/utils/cython/render.pyx**, then re-compile file

Thank you very much for your answer, the problem has been solved

**Comment by NiccoBiondi** [comment]
Hi, 

even with `cdef numpy.ndarray[double, ndim=3, mode='c'] image = numpy.empty((h, w, c), dtype=numpy.double)` the problem is still present. 
Do you have any other possible fix for that?
